"""
veriform.detector.state_tracker
===============================
DOM state differencing engine for the workflow runtime.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from datetime import datetime, timezone
from typing import Any

from veriform.detector.detector import detect_fields
from veriform.models.schemas import FieldSchema
from veriform.models.workflow import StateSnapshot

# Selectors from executor.py for validation messages
_VALIDATION_SELECTORS: tuple[str, ...] = (
    "[role='alert']",
    "[aria-live='polite']",
    "[aria-live='assertive']",
    ".error",
    ".invalid",
    ".validation-error",
    ".field-error",
    "[aria-invalid='true']",
    ".help-block",
    ".form-error",
)


async def capture_state(page: Any, run_id: str) -> StateSnapshot:
    """Capture the current semantic DOM state into a StateSnapshot."""
    url = page.url
    
    # 1. Extract interactive fields
    fields = await detect_fields(page, run_id)
    
    # 2. Extract validation messages
    validation_messages = await _extract_all_validation_messages(page)
    
    # 3. Compute semantic state hash
    state_hash = _compute_semantic_hash(url, fields, validation_messages)
    
    return StateSnapshot(
        state_id=f"snap_{uuid.uuid4().hex[:8]}",
        state_hash=state_hash,
        url=url,
        timestamp=datetime.now(tz=timezone.utc),
        active_fields=fields,
        validation_messages=validation_messages,
    )


async def _extract_all_validation_messages(page: Any) -> list[str]:
    """Find all active validation messages on the page."""
    messages = set()
    for sel in _VALIDATION_SELECTORS:
        try:
            locators = await page.locator(sel).all()
            for loc in locators:
                text = await loc.inner_text(timeout=100)
                if text and text.strip():
                    messages.add(text.strip())
        except Exception:
            pass
    return sorted(list(messages))


def _compute_semantic_hash(
    url: str,
    fields: list[FieldSchema],
    validation_messages: list[str],
) -> str:
    """
    Compute a stable identity hash representing semantic equivalence.
    Ignores dynamic timestamps, nonces, animations.
    Goal = semantic state equivalence, not exact HTML equality.
    """
    # Create a stable representation of fields
    field_reps = []
    for f in fields:
        # Ignore dom_id as it might be randomly generated by frameworks (e.g. react-aria-id-123)
        # Rely on name, type, required, and structural constraints.
        field_reps.append({
            "name": f.name,
            "type": f.type,
            "required": f.required,
            "min_length": f.min_length,
            "max_length": f.max_length,
            "pattern": f.pattern,
        })
    
    # Sort to ensure stable hash even if DOM order changes slightly, 
    # but usually form order is semantic. We will maintain DOM order 
    # to differentiate between identical fields in different sections.
    # Actually, DOM order is important. So we don't sort.
    
    state_payload = {
        # Optional: strip query params or fragments if they are non-semantic?
        # For now, we include base path.
        "path": url.split("?")[0].split("#")[0], 
        "fields": field_reps,
        "validation_messages": validation_messages,
    }
    
    raw = json.dumps(state_payload, sort_keys=True)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]
